# Generated by Django 5.0.3 on 2024-03-31 19:42

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('price', models.FloatField()),
                ('old_price', models.FloatField()),
                ('description_product', models.TextField(max_length=500, null=True)),
                ('count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('path', models.CharField(max_length=100)),
                ('product', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='myProdject.products')),
            ],
        ),
        migrations.CreateModel(
            name='Features',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100, null=True)),
                ('product', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='myProdject.products')),
            ],
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=500, null=True)),
                ('product', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='myProdject.products')),
            ],
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(default='anonymous', max_length=30)),
                ('user_comment', models.TextField(default='no', max_length=500)),
                ('user_rating', models.IntegerField(validators=[django.core.validators.MaxValueValidator(9)])),
                ('date', models.DateTimeField()),
                ('product', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='myProdject.products')),
            ],
        ),
        migrations.CreateModel(
            name='Similar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='product_original', to='myProdject.products')),
                ('sim_product', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='product_similar', to='myProdject.products')),
            ],
        ),
    ]
